### 배열 생성하기

In [1]:
!pip install numpy  # ! :cell에서 터미널 쪽에 명령어, 
                    # python install package: pip
                    # install :명령어, uninstall: 도 있다

In [2]:
# 주피터로 변경될 때가 있었는데, 그럴 때 경로에 해당하는게 굉장히 중요했다. 
#아니콘다 , 파이참 쓸때도, 호환되게끔 잘, 경로에 대해서 잘 알아야 쓸 수 있다. 
#알아두시면 좋을 듯 패키지는 여기에 설치

In [1]:
import numpy as np

In [5]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [6]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [7]:
data3 = [3, 0.1, 5, 4, 12, 0.5]
a3 = np.array(data3)
a3

array([ 3. ,  0.1,  5. ,  4. , 12. ,  0.5])

In [8]:
a1.dtype # data type

dtype('int32')

In [9]:
a2.dtype 

dtype('float64')

In [11]:
np.array([0.5, 2, 0.01, 8]) 
# 내장 함수의 리스트 데이터 형:  강제 형변환 -> 같은 종류로 형변환(실수형)
# array : numpy 패키지 안에 있는 것 / 순서가 있고 같은 자료형
# 자리수가 가장 긴 경우로 잡더라 -> 연산할 때 좋다. 보기 편하라고

array([0.5 , 2.  , 0.01, 8.  ])

In [18]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
a[1,1]

5

In [16]:
a[2,2]

9

In [14]:
np.array([[0.01,2,3],[4,5,6],[7,0.08,9]])

array([[0.01, 2.  , 3.  ],
       [4.  , 5.  , 6.  ],
       [7.  , 0.08, 9.  ]])

#### 범위를 지정해 배열 생성

In [19]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [20]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
np.arange(12).reshape(4,3) # 행렬: 2차원으로 만들어줘

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
np.arange(10).reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [25]:
np.arange(12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [27]:
b1 = np.arange(12).reshape(4,3)
b1.shape # 사이즈 보기

(4, 3)

In [3]:
b2 = np.arange(5)
b2.shape


(5,)

In [6]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [8]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

#### 특별한 형태의 배열 생성

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((3,5))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 배열의 데이터 타입 변환

In [17]:
np.array(['1.5', '0.62', '2','3.14','3.141593'])

array(['1.5', '0.62', '2', '3.14', '3.141593'], dtype='<U8')

In [18]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9','8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [19]:
str_a1.dtype #unsigned 보호가 없는 , 5미만

dtype('<U5')

In [20]:
num_a1.dtype #float 형변환이 잘 되었다라는 것

dtype('float64')

In [21]:
str_a2 = np.array(['1', '3', '5', '7','8'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 8])

In [23]:
str_a2.dtype

dtype('<U1')

In [24]:
num_a2.dtype

dtype('int32')

In [25]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_i1 = num_f1.astype(int)
num_i1

array([10, 21,  0,  4,  5])

In [26]:
num_f1.dtype

dtype('float64')

In [27]:
num_i1.dtype

dtype('int32')

#### 난수 배열의 생성

In [28]:
np.random.rand(2,3)

array([[0.34793996, 0.80789112, 0.32417335],
       [0.0937353 , 0.57275801, 0.8092523 ]])

In [29]:
np.random.rand()

0.8175194150690404

In [30]:
np.random.rand(2,3,4) # 3*4열 세트가 두 개 있다

array([[[0.19512218, 0.72327177, 0.16788866, 0.10102101],
        [0.62409557, 0.86879244, 0.85702123, 0.80912614],
        [0.26484049, 0.33261035, 0.23926365, 0.74361307]],

       [[0.44630698, 0.18868838, 0.12814037, 0.2061607 ],
        [0.44654652, 0.50574566, 0.68829478, 0.75481204],
        [0.8666797 , 0.92111525, 0.91190532, 0.46068646]]])

In [31]:
np.random.randint(10, size = (3,4))

array([[1, 1, 8, 3],
       [8, 1, 9, 3],
       [2, 7, 3, 3]])

In [32]:
np.random.randint(1,30)

5

### 배열의 연산

#### 기본연산

In [33]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [34]:
arr1 + arr2

array([11, 22, 33, 44])

In [35]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [36]:
arr2 * 2

array([2, 4, 6, 8])

In [37]:
arr2 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [38]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [41]:
arr2 * 2

array([2, 4, 6, 8])

In [42]:
arr2 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [43]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [44]:
arr1/(arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [48]:
arr1

array([10, 20, 30, 40])

In [49]:
arr1 > 20

array([False, False,  True,  True])

#### 통계를 위한 연산

In [51]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [52]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [53]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [54]:
[arr3.min(), arr3.max()]

[0, 4]

In [56]:
arr4= np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [57]:
arr4.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [58]:
arr4.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

#### 행렬 연산

In [59]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [60]:
B = np.array([3,2,1,0]).reshape(2,2)
B

array([[3, 2],
       [1, 0]])

In [61]:
A.dot(B)

array([[1, 0],
       [9, 4]])

In [62]:
np.dot(A,B)

array([[1, 0],
       [9, 4]])

In [63]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [64]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [65]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [66]:
np.linalg.det(A)

-2.0

In [100]:
a = np.array([1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [101]:
a[(a % 2) == 0]

array([2, 4, 6])

In [102]:
b1 = np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [103]:
b1[:3]

array([ 0, 10, 20])

In [104]:
b1[2:]

array([20, 30, 40, 50])

In [105]:
b1[2:5] = np.array([25,35,45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [107]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [111]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [112]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [113]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [114]:
b2[1][0:2]

array([40, 50])

In [116]:
b2[0:2, 1:3] = np.array([[25,35],[55,65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])